IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_NAME = 'GetAllLocations')
DROP PROCEDURE [dbo].[GetAllLocations]
GO
CREATE PROCEDURE [dbo].[GetAllLocations]
AS
    SELECT * FROM Location