IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_NAME = 'GetPersonById')
DROP PROCEDURE [dbo].[GetPersonById]
GO
CREATE PROCEDURE [dbo].[GetPersonById]
    @id UNIQUEIDENTIFIER
AS
    SELECT * FROM Person WHERE userId = @id;