IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_NAME = 'GetUserById')
DROP PROCEDURE [dbo].[GetUserById]
GO
CREATE PROCEDURE [dbo].[GetUserById]
    @id UNIQUEIDENTIFIER
AS
    SELECT * FROM AirBnbUser WHERE id = @id;